/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;
import org.tmf.dsmapi.common.impl.BadUsageExceptionMapper;
import org.tmf.dsmapi.common.impl.JacksonConfigurator;

/**
 *
 * @author pierregauthier
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiListingResource.class);        
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ResourceListingProvider.class);
        resources.addAll(getRestResourceClasses());
        return resources;
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(org.tmf.dsmapi.common.impl.BadUsageExceptionMapper.class);
        resources.add(org.tmf.dsmapi.common.impl.JacksonConfigurator.class);
        resources.add(org.tmf.dsmapi.inventory.resource.impl.EquipmentFacadeREST.class);
        resources.add(org.tmf.dsmapi.inventory.resource.impl.ResourceFacadeREST.class);
        resources.add(org.tmf.dsmapi.inventory.resource.impl.TopologicalLinkFacadeREST.class);
        resources.add(org.tmf.dsmapi.inventory.resource.impl.TpeFacadeREST.class);
        // following code can be used to customize Jersey 1.x JSON provider:
        try {
            Class jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return resources;
    }
    
}

  
